//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace APP_NETLINK.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class BD_NETLINKEntities1 : DbContext
    {
        public BD_NETLINKEntities1()
            : base("name=BD_NETLINKEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Categoria> Categoria { get; set; }
        public virtual DbSet<director> director { get; set; }
        public virtual DbSet<genero> genero { get; set; }
        public virtual DbSet<Idioma> Idioma { get; set; }
        public virtual DbSet<multimedia> multimedia { get; set; }
        public virtual DbSet<pais> pais { get; set; }
        public virtual DbSet<PeliculasPorVer> PeliculasPorVer { get; set; }
        public virtual DbSet<rol> rol { get; set; }
        public virtual DbSet<serie> serie { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<tipo_multimedia> tipo_multimedia { get; set; }
        public virtual DbSet<usuario> usuario { get; set; }
    }
}
