//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace APP_NETLINK.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class serie
    {
        public int id_serie { get; set; }
        public Nullable<int> id_multimedia { get; set; }
        public Nullable<int> capitulo { get; set; }
        public string titulo { get; set; }
    
        public virtual multimedia multimedia { get; set; }
    }
}
